# This is a sample build configuration for Scala.
image: bitbucketpipelines/scala-sbt:scala-2.12

pipelines:
  default:
    - step:
        caches:
          - sbt
          - ivy2
        script: # Modify the commands below to build your repository.
          - sbt fullOptJS
